version: '3.8'

services:
  db:
    image: postgres:14
    container_name: aquvit-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: aquvit_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  server:
    image: postgrest/postgrest
    container_name: postgrest-local
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/aquvit_test
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: reallyreallyreallyreallyverysafeandsecurejwtsecret
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
